"""Initial migration

Revision ID: 620482aafa63
Revises: 
Create Date: 2026-01-23 14:44:46.929787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620482aafa63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # school
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_domain'), 'school', ['domain'], unique=True)
    op.create_index(op.f('ix_school_id'), 'school', ['id'], unique=False)
    op.create_index(op.f('ix_school_name'), 'school', ['name'], unique=False)

    # role
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)

    # user
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)

    # academicyear
    op.create_table('academicyear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Draft', 'Archived', name='yearstatus'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academicyear_id'), 'academicyear', ['id'], unique=False)
    op.create_index(op.f('ix_academicyear_name'), 'academicyear', ['name'], unique=True)

    # evoucher
    op.create_table('evoucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Unused', 'Reserved', 'Used', 'Expired', 'Revoked', name='voucherstatus'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('reserved_at', sa.DateTime(), nullable=True),
    sa.Column('reserved_session_id', sa.String(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_student_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academicyear.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evoucher_id'), 'evoucher', ['id'], unique=False)
    op.create_index(op.f('ix_evoucher_reserved_session_id'), 'evoucher', ['reserved_session_id'], unique=False)
    op.create_index(op.f('ix_evoucher_voucher_number'), 'evoucher', ['voucher_number'], unique=True)

    # voucherattemptlog
    op.create_table('voucherattemptlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_number_entered', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('result', sa.Enum('Valid', 'InvalidPIN', 'NotFound', 'Expired', 'Used', 'Reserved', name='voucherattemptresult'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucherattemptlog_id'), 'voucherattemptlog', ['id'], unique=False)
    op.create_index(op.f('ix_voucherattemptlog_voucher_number_entered'), 'voucherattemptlog', ['voucher_number_entered'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
