"""add address and city to student

Revision ID: 0e860fc9f377
Revises: 4e0d1f191eac
Create Date: 2026-01-29 14:18:41.070467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e860fc9f377'
down_revision: Union[str, Sequence[str], None] = '4e0d1f191eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardian', sa.Column('secondary_phone', sa.String(), nullable=True))
    op.add_column('guardian', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('student', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('student', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'city')
    op.drop_column('student', 'address')
    op.drop_column('guardian', 'occupation')
    op.drop_column('guardian', 'secondary_phone')
    # ### end Alembic commands ###
