"""Add missing ghana_card and disability_status to student

Revision ID: 3865ce43eec6
Revises: 0e860fc9f377
Create Date: 2026-02-03 23:02:01.222226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3865ce43eec6'
down_revision: Union[str, Sequence[str], None] = '0e860fc9f377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('ghana_card', sa.String(), nullable=True))
    op.add_column('student', sa.Column('disability_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'disability_status')
    op.drop_column('student', 'ghana_card')
    # ### end Alembic commands ###
