"""Add term model and relationship

Revision ID: 9bb324ab4870
Revises: 620482aafa63
Create Date: 2026-01-27 16:34:20.621529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb324ab4870'
down_revision: Union[str, Sequence[str], None] = '620482aafa63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Active', 'Closed', name='termstatus'), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('result_open_date', sa.Date(), nullable=True),
    sa.Column('result_close_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academicyear.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_term_academic_year_id_start_date', 'term', ['academic_year_id', 'start_date'], unique=False)
    op.create_index(op.f('ix_term_id'), 'term', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_term_id'), table_name='term')
    op.drop_index('ix_term_academic_year_id_start_date', table_name='term')
    op.drop_table('term')
    # ### end Alembic commands ###
